---
 - hosts: all             #  this is target section 
   remote_user: root    # this is also target section 
   vars:              #  this is variable section 
    - x: httpd
   tasks:
    - name: running a command
      command: whoami

    - name: installing "{{ x }}"
      yum: name="{{ x }}"

    - name: starting "{{ x }}"
      service: name="{{ x }}" state=started  enabled=yes

    - name: copy index page to target machine 
      get_url: url=http://192.168.10.254/a.html dest=/var/www/html/index.html

    - name: flusing firewall rules
      shell: iptables  -F







